nginx:
    build: ./nginx
    container_name: docker_nginx
    ports:
        - "80:80"
    #     - "443:443"
    volumes:
        - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d:rw
        - /www/logs/nginx:/var/log/nginx:rw
        - /www/web:/var/www/html:rw
    links:
        - php-fpm-5.6:_DOCKER_PHP_FPM_5.6
        - php-fpm-7.1:_DOCKER_PHP_FPM_7.1
    
    # extra_hosts:
        # - "localhost:172.17.0.1"

php-fpm-5.6:
    container_name: docker_php-fpm-5.6
    build: ./php5.6
    expose:
        - "9000"

    links:
        - mysql
    volumes:
        - ./php5.6/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - /www/web:/var/www/html:rw

php-fpm-7.1:
    container_name: docker_php-fpm-7.1
    build: ./php7.1
    expose:
        - "9000"

    links:
        - mysql
    volumes:
        - ./php7.1/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
        - /www/web:/var/www/html:rw


mysql:
    container_name: docker_mysql
    build: ./mysql
    ports:
        - "3306:3306"
    environment :
        MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /www/data/mysql:/var/lib/mysql